---

- name: install OSQuery on Linux
  hosts: linux
  remote_user: student
  tasks:

     - name: install
       shell:  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
       register: output

     - name: add repo
       shell:  add-apt-repository "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/xenial xenial main"

     - name: update
       shell: apt update

     - name: install
       shell:  apt install osquery

     - name: start osquery
       shell: service osqueryd start

