---

- name: Installed Software
  hosts: linux
  remote_user: student
  tasks:
  
    - name: installed server components
      shell: 
      register: output
    
    - debug: var=output.stdout_lines
    
    - name: installed applications
      shell: osqueryi "select package from portage_packages;"
      register: output
      
    - debug: var=output.stdout_lines
    
    - name: boot software
      shell: osqueryi "select name from processes;"
      register: output
      
    - debug: var=output.stdout_lines
